In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv('Cutlets.csv')

In [5]:
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [6]:
#null hypothesis: there is no difference in dia of cutlets
#alt hypothesis : there is difference in dia of cutlets

In [8]:
a=pd.Series(df.iloc[:,0])

In [10]:
b=pd.Series(df.iloc[:,1])

In [11]:
a.head()

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [4]:
 from scipy import stats

In [5]:
from scipy.stats import norm

In [15]:
p_value= stats.ttest_ind(a,b)

In [16]:
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [17]:
#since p > alpha(0.05) 
#accept null hypotheis ,implies theres is no difference in dia of cutlets

In [ ]:
#labtat

In [18]:
data=pd.read_csv('LabTAT.csv')

In [19]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [20]:
# h0: thers is no difference in avg turn around time
#h1: theres difference in avg turn around time

In [27]:
p_value=stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

In [28]:
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [26]:
#p<alpha (0.05) implies reject null hyp, therfore there is differnce in avg TAT

In [ ]:
## customer order forms##

In [31]:
abc=pd.read_csv('Costomer+OrderForm.csv')

In [32]:
abc.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [33]:
from scipy.stats import chi2_contingency

In [34]:
abc['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [38]:
abc['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [39]:
abc['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [40]:
abc['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [50]:
ab=np.array([[271,267,269,280],[29,33,31,20]])

In [51]:
ab

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [43]:
#h0: the defective % does not varies by centre
#h1:the defective %  varies by centre

In [52]:
chi2_contingency(ab)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [49]:
#sinnce p(0.27)> alpha(0.05) accept null hypothesis i.e. the defective % does  not varies by centre

In [1]:
#buyers ratio

In [6]:
apd=pd.read_csv('BuyerRatio.csv')

In [7]:
apd

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [8]:
apd_table=apd.iloc[:,1:]
apd_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [10]:
val=stats.chi2_contingency(apd_table)

In [11]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [12]:
no_of_rows=len(apd_table.iloc[0:2,0])
no_of_columns=len(apd_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [13]:
Expected_value=val[3]

In [14]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [16]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(apd_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [17]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [ ]:
#since p is greater than  alpha accept null hypothesis